packages:
  - apps/*
  - packages/*
  - packages/react/*

catalog:
  '@tailwindcss/postcss': ^4.1.11
  '@turbo/gen': ^2.5.5
  '@types/node': ^24.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  eslint: ^9.32.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
