/* eslint-disable @typescript-eslint/no-unsafe-assignment */
// import {
//   Backpack,
//   CakeSlice,
//   Coffee,
//   Grape,
//   Hotel,
//   IceCream,
//   MapPin,
//   Package,
//   Pizza,
//   Plane,
//   Sandwich,
//   Smile,
// } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";

import {
  Item,
  Navbar,
} from "@forthtilliath/shadcn-ui/components/blocks/navbar-04";

import "@forthtilliath/shadcn-ui/globals.css";
import "@forthtilliath/shadcn-ui/themes/twitter.css";

// import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items: Item[] = [
  { href: "#", label: "Home" },
  {
    label: "Foods",
    href: "#",
    // items: [
    //   {
    //     label: "Dessert",
    //     icon: CakeSlice,
    //     href: "#",
    //     description: "Sweet treats to satisfy your cravings.",
    //   },
    //   {
    //     label: "Pizza",
    //     icon: Pizza,
    //     href: "#",
    //     description: "Delicious, cheesy slices of goodness.",
    //   },
    //   {
    //     label: "Sandwich",
    //     icon: Sandwich,
    //     href: "#",
    //     description: "Classic and hearty fast food options.",
    //   },
    //   {
    //     label: "Coffee",
    //     icon: Coffee,
    //     href: "#",
    //     description: "Your go-to boost of caffeine.",
    //   },
    //   {
    //     label: "Ice Cream",
    //     icon: IceCream,
    //     href: "#",
    //     description: "Cold, creamy delights for any mood.",
    //   },
    //   {
    //     label: "Fruit",
    //     icon: Grape,
    //     href: "#",
    //     description: "Fresh and healthy natural snacks.",
    //   },
    // ],
  },
  {
    label: "Travel",
    href: "#",
    // items: [
    //   {
    //     label: "Destinations",
    //     icon: MapPin,
    //     href: "#",
    //     description: "Discover amazing places to visit.",
    //   },
    //   {
    //     label: "Hotels",
    //     icon: Hotel,
    //     href: "#",
    //     description: "Find the best stays for your trips.",
    //   },
    //   {
    //     label: "Flights",
    //     icon: Plane,
    //     href: "#",
    //     description: "Get deals and tips on air travel.",
    //   },
    //   {
    //     label: "Packing",
    //     icon: Package,
    //     href: "#",
    //     description: "Essential checklists for stress-free packing.",
    //   },
    //   {
    //     label: "Activities",
    //     icon: Smile,
    //     href: "#",
    //     description: "Exciting things to do wherever you go.",
    //   },
    //   {
    //     label: "Travel Tips",
    //     icon: Backpack,
    //     href: "#",
    //     description: "Make every trip smooth and memorable.",
    //   },
    // ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar
          logo={<h1>Logo</h1>}
          items={items}
          render={({ href, label }) => <Link href={href}>{label}</Link>}
          // renderSubItem={(item) => (
          //   <Link href={item.href} className="flex items-center gap-2">
          //     <item.icon className="h-5 w-5 mr-2 text-muted-foreground" />
          //     {item.label}
          //   </Link>
          // )}
        />
        {children}
      </body>
    </html>
  );
}
