import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";

import {
  Item,
  Navbar,
} from "@forthtilliath/shadcn-ui/components/blocks/navbar-02";

import "@forthtilliath/shadcn-ui/globals.css";
import "@forthtilliath/shadcn-ui/themes/twitter.css";

// import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "@forthtilliath Web",
  description: "Generated by create next app",
};

const items: Item[] = [
  { href: "#", label: "Home" },
  {
    label: "Foods",
    href: "#",
  },
  {
    label: "Travel",
    href: "#",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar
          logo={<h1>Logo</h1>}
          items={items}
          render={({ href, label }) => <Link href={href}>{label}</Link>}
        />
        <main className="container p-8">{children}</main>
      </body>
    </html>
  );
}
